name       : haskell-integer-simple
version    : 0.1.1.1
release    : 5
source     :
    - http://hackage.haskell.org/package/integer-simple-0.1.1.1/integer-simple-0.1.1.1.tar.gz : 766b4b9de5c5c7cf77191b32462155b3c7bd34d035abb1af5f6369cb097510fd
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package contains an simple Integer library.
description: |
    This package contains an simple Integer library.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
