name       : haskell-integer-simple
version    : 0.1.1.1
release    : 1
source     :
    - http://hackage.haskell.org/package/integer-simple-0.1.1.1/integer-simple-0.1.1.1.tar.gz : 766b4b9de5c5c7cf77191b32462155b3c7bd34d035abb1af5f6369cb097510fd
license    : BSD-3-Clause
component  : programming
summary    : This package contains an simple Integer library.
description: |
    This package contains an simple Integer library.
builddeps  :
    - ghc
setup      : |
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 integer-simple-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/integer-simple-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/integer-simple-$version/*.a
